#!/bin/bash
tyler-down;
echo Restarting the platform...;
cwd=$(pwd);
cd ~/spy/platform-dev-environment-compose;
sudo docker-compose down;
sudo docker-compose up -d;
cd $cwd; echo Up complete!;
tyler-up;